name: python-code-visualiser
author: mike@trebilcock.net
description: 'Create Mermaid diagrams from Python code'
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  gh-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
  - name: install nightly
    run: |
      rustup set profile minimal
      rustup toolchain install nightly
    shell: bash
  - name: build pymermaider
    run: |
      git clone https://github.com/diceroll123/pymermaider
      cd pymermaider
      cargo build --release
    shell: bash
  - name: run pymermaider
    run: |
      pymermaider/target/release/pymermaider
    shell: bash
  - name: upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name: mermaid-diagrams
      path:
        pymermaider/target/release/output/*.md
  - name: Upload mermaid md file diagram into PR
    uses: actions/github-script@v7
    with:
      github-token: ${{ inputs.gh-token }}
      script: |
        const fs = require('fs');
        const body = fs.readFileSync('pymermaider/target/release/output/*.md', 'utf8');
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: '```mermaid\n' + body + '\n```' 
        })



