name: Test Uploading Mermaid Diagrams

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Example Diagrams
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install nightly
      run: |
        rustup set profile minimal
        rustup toolchain install nightly
      shell: bash
    - name: build pymermaider
      run: |
        git clone https://github.com/diceroll123/pymermaider
        cd pymermaider
        cargo build --release
      shell: bash
    - name: run pymermaider
      run: |
        pymermaider/target/release/pymermaider .
        cat ./output/${{ github.event.repository.name }}.md
      shell: bash
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mermaid-diagrams
        path:
          ./output/${{ github.event.repository.name }}.md
    - name: Upload mermaid md file diagram into PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ./output/${{ github.event.repository.name }}.md
        comment_tag: 'mermaid-diagram'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}